### ISSUE TITLE
Leatrix Plus/Maps Icon showing on minimap: possible to disable?

### ISSUE THREAD

**Issue by Stormbrain24** [leatrix/leatrix-plus#110]
Drargonflight is now live and I am loving leatrix as always but I noticed that on the minimap there's an icon other than the minimap icon for leatrix that wont disappear.  When you have both plus and maps installed it shows up as a number 2 on the minimap and I cannot for the life of me find a way to disable it as I am finding it a little distracting

**Comment by leatrix** [comment]
This is the new addon compartment menu that Blizzard added to the game in Dragonflight.  It's nothing to do with Leatrix Plus.  The compartment menu will be shown if you have any addons installed which make use of it.

The point of the compartment menu is to consolidate minimap buttons.  So addon authors no longer need to create their own minimap buttons for their addons.  They can simply have their addons listed in the compartment menu instead.

The number indicates the number of addons registered to the compartment menu.  You are seeing number 2 because you have 2 addons installed that make use of the compartment menu (LTP and LTM).  If you have no addons installed which make use of the compartment menu, you won't see the menu at all which is why you don't see it when you disable LTP and LTM.

However, as more addons are updated for Dragonflight, they will probably start to make use of the compartment menu and it may be the only way to access addon configuration panels in future.

If you have 'Enhance minimap' enabled and you are using 'Square minimap', the compartment menu will hide when your pointer is not over the minimap (it currently shows on startup but that's fixed in the latest alpha).

LTP and LTM still have regular minimap buttons available because some people prefer them to the compartment menu but you can hide the buttons in the addon settings and just use the compartment menu if you prefer.

In future, as more addons make use of the compartment menu, it should end up looking something like this (with different icons):
![image](https://user-images.githubusercontent.com/58888415/198000366-83e1189b-f635-4edd-9286-062da09f17ff.png)

**Comment by Stormbrain24** [comment]
Ah thanks for the info!

**Comment by Stormbrain24** [comment]
Yeah I noticed, I was the one to mention it :D

**Comment by leatrix** [comment]
In 10.0.01, there is a new setting in the 'Enhance minimap' configuration panel to hide the addon menu (the compartment menu).  It's enabled by default so if you don't want to see the compartment menu, you don't have to do anything other than update the addon.

Further, Leatrix addons will no longer register with the compartment menu (at least, not until it's clearer what the future is for the compartment menu, if any).
