### ISSUE TITLE
"Faster auto loot" with chat frame error bug

### ISSUE THREAD

**Issue by Zifijo** [leatrix/leatrix-plus#113]
Hello. I recently started receiving this bug anytime I would auto loot mobs or chests. Even when i opened loot bags. It will post the "NO QUALITY LOOT nil" message twice. I narrowed it down to the Leatrix Plus add on with Faster auto loot option enabled. I tried this with everything else disabled and managed to narrow it down.  I was able to replicate this numerous times. I have attached a SS of the issue.
![WoWScrnShot_102622_131003](https://user-images.githubusercontent.com/116751135/198091780-411263b1-0a93-41e8-8c39-fd6e26688758.jpg)

**Comment by leatrix** [comment]
Thanks for your report and troubleshooting steps.  It's very helpful.  The issue is caused by the game code so for now, all you can do is report it to Blizzard using the in-game bug report tool.  

Perhaps they are debug messages left in the game by mistake because the messages are in English and I don't know what they would expect a player to do with debug messages anyway.

Report it to Blizzard and hopefully they will fix it.  The issue to note in your report is that LootFrameMixin:Open() contains debug print statements which output messages in English and perhaps they have been left in the game code by mistake.  The messages are printed when addons attempt to loot higher quality items.

**Comment by leatrix** [comment]
https://us.forums.blizzard.com/en/wow/t/no-quality-loot-nil-error/1380801

**Comment by Grapefruit82** [comment]
Thanks for the reply, Leatrix! Funny enough I'm the "craig" that requested this option all those years ago!

I understand that this is a game code side issue, but at the same time it only happens when I run "faster auto loot". Does the new patch/version not like the "trick" this fast loot does? I also replied to the Blizz thread above, thank you.

I still love the option, especially now that default loot takes even longer to scroll through the items.

**Comment by leatrix** [comment]
Since the print statements are in the game code, it makes sense that you would sometimes see them without any addons too.

This game code is the cause of it:
```
if not itemQuality then
	print("NO QUALITY LOOT "..tostring(item)..", currencyID"..tostring(currencyID)..", quantity"..tostring(quantity)..", slotIndex"..tostring(slotIndex)..", isCoin"..tostring(isCoin));
end
```

This code exists in the latest live game (10.0.0.46313) and the BETA for Dragonflight launch (10.0.2.46259).

Who knows why they felt it necessary to have print statements that output English messages in the loot code.  It isn't like players are going to debug the loot frame themselves.

It's affecting a lot of players, Blizzard are aware of the problem, it's technically spam from the game code and it's very easy for them to fix (delete or comment out the print statements) so just keep pestering them until they fix it.

**Comment by leatrix** [comment]
In the latest release (10.0.06), you can now toggle the fix for Blizzard's NO QUALITY LOOT spam using a new setting in the 'Faster auto loot' configuration panel.

**Comment by leatrix** [comment]
I'm happy to report that Blizzard have finally removed their NO QUALITY LOOT spam code from game version 10.0.2.46702 so the LTP setting to disable the spam has been removed in the latest alpha (currently 10.0.12.alpha.2).
