### ISSUE TITLE
Numbers under Calendar 

### ISSUE THREAD

**Issue by kingreboot** [leatrix/leatrix-plus#120]
I have a number and button that shows both leatrix plus and map. How do I remove them 
![Screenshot_2022-10-26_125215](https://user-images.githubusercontent.com/24847320/198205504-fc28724b-c1a5-46ff-9bb3-34980a50e3bc.png)

**Comment by ceddya** [comment]
Yup, I have the same issue. Is there any way to hide the number?

**Comment by Daeveren** [comment]
Was about to create an issue about this too. Please let us remove this.

![dsW6rfiAOU](https://user-images.githubusercontent.com/6321337/198223273-e0eb29b2-9f6d-483c-aa92-4c4f21ce3eb9.png)

**Comment by funkydude** [comment]
Hi, I am the developer of SexyMap, which it looks like the OP is using.
I was notified of Leatrix's opinions on this via this SexyMap bug report: <https://github.com/funkydude/SexyMap/issues/272>

In the latest update of SexyMap I am now force hiding this.

Here's a few reasons why devs should not use this:
1) It's fuck ugly. I cannot think of a worse way to execute this than slapping a number in a box and calling it a day.
2) You are forcing this method on the user without their choice. Previously, a user could "opt in" by using a separate addon to collect buttons.
3) The dropdown (besides also being ugly) is just not a good way to handle multiple addons (think 10-20+).
4) The dropdown will probably cause addon taint issues.
5) You leave yourself at the whim of Blizzard's future changes, future bugs, and future taint issues.

The concept/idea is obviously nice, that's why addons exist to do this.
As I'm also the dev of LibDBIcon, what I'm going to do in a future update is add a built-in way for addons to toggle a "one button" mode. That way addon devs can give users the choice of which mode to use at the flick of a switch, rather than relying on Blizz, or other addons.

**Comment by leatrix** [comment]
https://github.com/leatrix/leatrix-plus/issues/110
