### ISSUE TITLE
cant move buffs

### ISSUE THREAD

**Issue by zdhar** [leatrix/leatrix-plus#14]
hello, thank you for the addon
im also using basic minimap addon and i think there is conflict with it
i cant move buffs
any idea ?

**Comment by leatrix** [comment]
Disable all addons except Leatrix Plus.  It should work correctly.  Enable other addons again gradually until you find the one causing the problem.  I don't think it's BasicMinimap.

**Comment by zdhar** [comment]
sorry for the late, you were right and its SUI addon !!
Ty

**Comment by leatrix** [comment]
If you want to use 'Manage buffs' in Leatrix Plus along with SUI, there are a couple of options.

The first option is to disable 'Dark Frames' which you can do in the /sui configuration panel.  That prevents SUI from managing the buffs frame but it removes all dark frames so that's probably not what you want.

The second option is to prevent SUI from loading the buffs management code.  To do that, explore the SUI folder and open SUI.toc with Notepad.  Find the line **inc\core\buffs.lua** and prefix it with ## so it becomes **##inc\core\buffs.lua**.  Save and reload your UI.  SUI should no longer prevent Leatrix Plus from moving the buffs frame.

If would be worth creating an issue with SUI developer to ask them to add an option to disable buff frame management so that SUI does not conflict with other addons that manage the buffs frame.  The issue tracker for SUI is [here](https://www.curseforge.com/wow/addons/sui/issues).

If you don't want to do any of the above, you can just disable 'Manage buffs' in Leatrix Plus and click the reload button.

**Comment by zdhar** [comment]
amazing answer ! love all the informations.
Exactly, just found the dark theme is the issue, just posted a message to them.
i will modify the file then.
thanks a lot !!
