### ISSUE TITLE
Issue with auto-sell junk 

### ISSUE THREAD

**Issue by gythwulf** [leatrix/leatrix-plus#175]
When there is a gray item in your bag without a sale price, it never gives up trying to sell it. I ran into this with [Carefully Rolled Message].

**Comment by leatrix** [comment]
What version of LTP do you have installed (the version number is shown top-left of the configuration panel)?

**Comment by gythwulf** [comment]
10.0.16

**Comment by leatrix** [comment]
this seems to work fine for me.  Tested with [Crystallized Note](https://www.wowhead.com/item=10839/crystallized-note) and it works perfectly.  If you disable all other addons, does that help?

`/script DEFAULT_CHAT_FRAME:AddMessage("\124cff9d9d9d\124Hitem:200590::::::::70:::::\124h[Carefully Rolled Message]\124h\124r");`


`/script DEFAULT_CHAT_FRAME:AddMessage("\124cff9d9d9d\124Hitem:10839::::::::70:::::\124h[Crystallized Note]\124h\124r");`

**Comment by gythwulf** [comment]
Unfortunately I didn't have the foresight to keep the item, so I can no longer test this.

That said, I noticed something peculiar: [Carefully Rolled Message] reports to have a vendor price of 1c, but it cannot be vendored. I wonder if that is a bug with the item on Blizzard's end.

**Comment by leatrix** [comment]
Wowhead reports that it has a sell price of 1 copper but the in-game link (above) reports it has no sell price (so presumably cannot be sold).  So it maybe the game is tagging the item incorrectly (game bug perhaps).

In 10.0.18.alpha.2 and higher, LTP will no longer attempt to sell Carefully Rolled Message (item ID: 200590) so that should solve the problem.

**Comment by leatrix** [comment]
Please try 10.0.19.alpha.1 and let me know if that fixes the problem.  In CurseForge App, right-click Leatrix Plus in your addon listing and change the release type to alpha to get this update.

The problem is caused by the game reporting that the items you listed have a sell price when in fact they cannot be sold.

**Comment by leatrix** [comment]
In that case, please try 10.0.19.alpha.3.

**Comment by gythwulf** [comment]
It only tries to sell the item once, which given the circumstances I believe is best case scenario.

**Comment by leatrix** [comment]
This only seems to affect 7 grey quest items that were all added in the same game patch (10.0.0.46247).  5 of them are for [Continued Waygate Exploration](https://www.wowhead.com/search?q=continued%20waygate%20exploration) and the other 2 are for [Dirty Old Satchel](https://www.wowhead.com/item=200592/dirty-old-satchel).  So in 10.0.19.alpha.4, because no other items seem to be affected and because this issue seems to be restricted to only a couple of quests from the same area that were added in the same patch, the 7 items are now whitelisted by their item IDs.
