### ISSUE TITLE
[Feature request] Junk autosell exception for gear

### ISSUE THREAD

**Issue by Sluimerstand** [leatrix/leatrix-plus#194]
With 10.0.5 introducing the ability to learn appearances from poor-quality gear, having an option to exclude these from the junk autosell would be great.

**Comment by leatrix** [comment]
A filter for junk item armor and weapon appearances is a good idea.

**Comment by leatrix** [comment]
In 10.0.25.alpha.5 when logged into the 10.0.5 PTR, grey transmogable armor and weapons that you have not collected the appearance for on any character will not be sold.  Once a character equips the item and learns the appearance, it will be sold in future.

If you have an item that you cannot equip (such as a shield when playing a mage) and have not collected the appearance for, it won't be sold so that you can send the item to a character that can equip it and then collect the appearance.  After the appearance is learned, the item will be sold in future.

There is also a new setting to exclude all grey armor and weapons in case you want to save them for 10.0.5 (for collecting the appearance or for putting them in the auction house).  This setting is in the addon now and does not require the 10.0.5 PTR.
