### ISSUE TITLE
Question about custom sound mute

### ISSUE THREAD

**Issue by SiderealDay** [leatrix/leatrix-plus#200]
Thanks for all work,

I was wondering about the new mute feature. Is it possible to mute certain sound effects that certain mobs make?

Specifically this mob: Cliffside Bullyswog
https://www.wowhead.com/npc=198419/cliffside-bullyswog#sounds
It is super annoying when trying to fish near it.

I tried plugging in all the numbers I saw under sounds tab, and even the numbers in the title: sound=19xxxx, to no avail.
I downloaded the Leatrix Sounds addon but could not find anything there, maybe I don't know what I am searching for?

If this is possible, please tell me how so I can add other sounds too :)

Any help is appreciated.

**Comment by leatrix** [comment]
For the page you linked, browse the activity column.  If you want to mute fidget sounds (for example), click each of the links which show fidget in the activity column.

For each link opened, you will see a list of sound files.  Ignore the FILEDATA_ prefix and just copy the numeric ID and paste it into the new 'Mute custom sounds' ('System') option (added in 10.0.26).  If you want to listen to the sound file first, paste the ID into Leatrix Sounds (maybe Leatrix Plus needs a listen to this sound file ID button...).

The reason that you can't find or mute the sound= ID shown in the address bar is because that is a sound kit ID, not a sound file ID.  The sound links on the page you linked are actually sound kit links.  Not sound file links.  Clicking on each of the sound kit links will show you the sound files that belong to that sound kit.

You cannot mute sounds by sound kit ID.  You can only mute sounds by sound file ID.  Since Blizzard stopped naming their sound kits, Wowhead are naming sound kits after the first sound file in the kit.  This is perhaps what is confusing you.

**Comment by SiderealDay** [comment]
Ty,

I found the right set of sounds. In this case, it was the 1st and 2nd set of figet sounds on wowhead.
