### ISSUE TITLE
Bug report: Tooltip unit target in raid environment

### ISSUE THREAD

**Issue by Rezy942** [leatrix/leatrix-plus#208]
When using Leatrix's tooltip  "show the units target" option - everything works fine, except when in a raid environment. (whenever there is a boss targeting multiple people at once as example).
Doing Grand Hunt, i notice this bug every few minutes.

What happens is the boss rapidly targets multiple people, and the tooltip somehow cant catch up.
The target names then expand down beyond the bottom of tooltip.
I could not capture it because it happens so rapidly, but here is a screenshot example:

![image](https://user-images.githubusercontent.com/122007087/210852395-979d3802-c3b1-41ca-b755-71044a3928a3.png)
The red circles is where additional targets go.

Solution: restrict max lines of targets to 1 (if possible), to prevent multiple targets.
No tooltip modifying addons are being used here btw.

Thank you!

**Comment by leatrix** [comment]
Are you using Threat Plates or another nameplate addon?

**Comment by Rezy942** [comment]
Here is an example of the bug:
![image](https://user-images.githubusercontent.com/122007087/210927376-5abd4a39-43e8-4a0f-bf98-29060d052599.png)

I have used threat plates in the past... but I do not have it installed now.
Do you think it might be caused by some left over things like cvars?
Perhaps /console cvar_default will fix this? i was hoping not to reset everything back... :(

**Comment by Rezy942** [comment]
After some messing around, turns out this is not Leatrix's fault.
It has to be related to one of the other addons im using. Weirdly none of them affect anything on tooltip except AllTheThings, which I tested is not the problem here.
With all addons off, tooltip works good.
I will try to mess around with it more and pin point it to one addon, but it will take time as its hard to reproduce.

Here is a list of my addons in case you might be aware of some incompatibility:
![image](https://user-images.githubusercontent.com/122007087/210928958-05d669eb-20a9-43f2-8cee-9f6157c1c427.png)
![image](https://user-images.githubusercontent.com/122007087/210928979-4e5a826d-912c-4bdc-865f-c4f03bf362c4.png)
![image](https://user-images.githubusercontent.com/122007087/210929000-adfcac99-e787-49d8-acb4-e0630f4a1db6.png)

**Comment by Rezy942** [comment]
Update: I was able to narrow it down to Instance Achievement Tracker addon (surprisingly).

Testing method: Run around Valdraken populated area near AH (~30-40 people my server) and rapidly hover over everyone to see if tooltip starts acting out. /reload when done and repeat process.

Leatrix Plus only enabled: 3-4 reloads, no issues with tooltip. Confirmed not the problem.
With only Leatrix Plus and Instance Achievement Tracker enabled: First reload ~ first 15 people ~2-3 tooltips acted out per screenshots above.
ALL addons enabled EXCEPT Instance Achievement Tracker: 3 reloads, no issues at all.

Looks like Instance Achievement Tracker? Is this something to fix on your end, or do you think its best to reach out to the addon dev?

Thank you

**Comment by leatrix** [comment]
I replicated it too with Instance Achievement Tracker installed.  When I disabled IAT, I could not replicate it.

Steps:

- Enable IAT and ensure the 'Enable addon' checkbox is checked in IAT configuration panel.
- Reload.
- Fly to a stationary mob (preferably in a low level area such as Elwynn Forest).
- Fly over the mob but don't enter combat.
- Put the pointer over the mob in the game world (not the unit frame) to show its tooltip and keep it there so the tooltip remains shown throughout.
- With the pointer over the mob, fly down (with X key).  When the mob attacks you, there's a reasonable chance that the bug will occur in the tooltip.  Sometimes, I saw just one line outside of the tooltip frame but sometimes there were many lines.
- If you see the bug, fly up (space bar) to leave combat so you can repeat.  If you don't see the bug, fly up to leave combat, put the pointer over the mob to show its tooltip and fly down again.  Keep doing that until the bug appears.  Sometimes, you might need to reload to see the bug.  Sometimes, the bug doesn't appear for a while.

Repeating this process with IAT disabled works fine.  It's probably something worth reporting to IAT.  Someone reported the issue to Threat Plates way back in November and the issue there was resolved.  Threat Plates works fine now.

The last version of Threat Plates that shows this bug is 11.1.1.  The bug appears to be fixed in 11.1.2.  The main difference appears to be that 11.1.2 started using the new tooltip API added in Wow 10.0.2.

**Comment by Rezy942** [comment]
Thank you so much for taking the time to reply about this. I've made a post at IAT github page with link to this post. Hopefully a resolution comes to pass soon.

**Comment by leatrix** [comment]
Please let me know how you go on with 10.0.28.alpha.4.

**Comment by Rezy942** [comment]
After few hours of gameplay and testing in the city, the issue disappeared!

**Comment by leatrix** [comment]
Awesome.  Thanks for your feedback and testing.
