### ISSUE TITLE
Show/hide raid button bug

### ISSUE THREAD

**Issue by J-Aitch** [leatrix/leatrix-plus#212]
Show /hide raid button is not visable in game but only shows in edit mode.  Once you hide the group there is no way to show them again without disabling show raid button again unless you go into edit mode.
Cheers J

**Comment by leatrix** [comment]
Are you actually in a raid group?  It only shows when you are in a raid group.

**Comment by J-Aitch** [comment]
I was in a raid group and went to click on show but the button was not showing up. Thats when I noticed the problem.

**Comment by leatrix** [comment]
I tested it and it's fine so you were probably in a party group still.

All the 'Show raid button' option does is move the default UI 'Show' button out of the raid management frame.  It doesn't actually control whether the button is shown or not.  The default UI handles that just like it does when 'Show raid button' is disabled.  

You can't see the button in a party group because the default UI party management frame doesn't have a 'Show' button.  It only appears in the raid management frame when in a raid group.
