### ISSUE TITLE
Recent update messing with Transmog window.

### ISSUE THREAD

**Issue by Mhortai** [leatrix/leatrix-plus#222]
After the recent update leatrix is putting a bar in the spot of my weapons in the transmog window, sometimes so I can't even access the slot to transmog my weapon slot at all.  This goes away when I disable leatrix.  The bar in the screenshots in the weapon slot in the transmog window only shows up when leatrix is enabled.
![WoWScrnShot_020423_140158](https://user-images.githubusercontent.com/104932444/216787872-f06f3656-d3f0-476c-bb4c-63a8ee29cb58.jpg)
![WoWScrnShot_020423_141046](https://user-images.githubusercontent.com/104932444/216787873-41a11ddd-3bc7-4c20-9a27-902603b82526.jpg)

**Comment by Mhortai** [comment]
Nvm I see the Enhance Dressup option now.  Fixed it.

**Comment by leatrix** [comment]
Just for anyone who may see this in future.  The transmogrify weapon slots have not been removed.  They are now shown in the right-side column so that you have a better view of your character.

10.0.35 - 4th February 2023
- For 'Enhance dressup' ('Interface'), there are new options for the transmogrify character preview.  You can make the character preview wider (enabled by default), increase the maximum zoom out distance (disabled by default) and show a character model animation slider (enabled by default).  The weapon slots are now shown in the right-side column to give a better view of your character.
