### ISSUE TITLE
New unified Leatrix Plus doesn't load in Classic SOD (Classic Era)

### ISSUE THREAD

**Issue by Motowatch** [leatrix/leatrix-plus#232]
### Issue

The new unified Leatrix Plus doesn't load in Classic SOD. Just does not load.

### Game version

Classic Era

**Comment by Jhaego** [comment]
definitely also does *not* work in non-SoD Classic. (':

**Comment by leatrix** [comment]
It works fine.  Make sure you have the right version installed.  The code is not unified.  There are still separate releases for The War Within, Cataclysm Classic and Classic Era.  Remove the version you have and install the correct version.

**Comment by Jhaego** [comment]
Ah, you are correct indeed. thank you!

**Comment by Jaysmoke420** [comment]
I went on the CurseForge app and deleted the version you kept spamming i needed to remove even though it worked fine. I then found and installed the version you say to use that says classic. Log into game, LTP does not show up at all in my addons or anywhere other than on the CurseForge app. I see here you telling people to install the right one, well mine says classic so now what? I only see one version of it on CurseForge when I brose in classic and thats the one i have. Old version was working great

**Comment by Himeki** [comment]
Same issue, I have "1.15.65-classic" and is not functioning in anniversary realm (classic era), same for the map addon

**Comment by Motowatch** [comment]
OKay, but I would say you need to change the text on the Curseforge page and your “Personal” page for the Leatrix addons. There is all kinds of wording that “no more multiple versions”, “just one version for all”, “download this one” after using link, and so forth. The current text and wording seems terribly misleading. 

I did mange to find the correct versions, but today I could not tell you how I did. It certainly is not obvious from the Cursreforge page or the “personal” pages that are linked to it. ^L^ Notice the other users agreeing with me. 

Only trying to help!

- Moto




On Dec 8, 2024, at 4:00 PM, leatrix ***@***.***> wrote:
It works fine. Make sure you have the right version installed. The code is not unified. There are still separate releases for The War Within, Cataclysm Classic and Classic Era. Remove the version you have and install the correct version.

**Comment by Walayimuna** [comment]
Mine is also not loading

I removed the previous version, installed the one that says 'use this one', and it doesn't even show up in-game

Here, on the curseforge:
![image](https://github.com/user-attachments/assets/a12d7d67-d019-4586-a200-e3fb723d3959)

In game:
![image](https://github.com/user-attachments/assets/44b377bf-69b9-4762-ab16-d5c4b9ccfbc1)

**Comment by Walayimuna** [comment]
Had to manually delete the addon for this to work

**Comment by leatrix** [comment]
The new addon works fine.  You just have to make sure that the old one is removed.  Once most people have removed the old addon, it can be retired - which is exactly why this process needs to happen as soon as possible and the in-game banner prompting everyone to move is essential.

Nobody likes in-game pop-ups which is why Leatrix addons don't have in-game change log popups and the like.  I don't like popups either.  But the sooner everyone switches to the new addons and removes the old ones, the better it will be for everyone.  I have been developing Leatrix addons for World of Warcraft players for nearly 15 years (your welcome) and in all that time, this is the first and only popup.  While most people have switched over to the new addons, some people have stopped using Leatrix addons because of that one and only popup but it had to be done.  People need to switch as soon as possible because it's not good to have multiple addons with the same addon folder name and game version so an in-game banner is the only way to achieve that.

If the old addon is gone from your addons folder and you only have the new one installed, there should be no further issues.
