### ISSUE TITLE
LTP prevents the TWW "The story so far" cinematic to play; a skip results in being stuck to black. (The War Within)

### ISSUE THREAD

**Issue by HerrTiSo** [leatrix/leatrix-plus#237]
### Issue

When enabled, either LTP or LTM prevents the TWW "the story so far" cinematic from being played upon character login, resulting in background ambience and wind noises being played, but only a black screen. Trying to skip the cinematic makes the client freeze completely. Tried on both MacOS and via GeForce Now. Disabling your add-ons fixes this behavior.

### Game version

The War Within

**Comment by leatrix** [comment]
Works fine for me.  Tested it just now.  Logged in, ported to Silithus, talked to Lady Jaina Proudmoore, asked her to play the movie, the movie played without issue.  Pressing space to skip the movie worked perfectly too.

The only option that affects cinematics in LTP is 'Faster movie skip' ('System').  If you disable that (or have it disabled already), does the problem still occur?  If so, I can't see how LTP is the cause of it.  Besides, you're saying the cinematic is a black screen so that setting won't do anything until you try to skip.

The Story So Far movie is in /ltp > Media > Movies >The War Within > The Story So far.  If you click that, does that work?  It works fine for me.

**Comment by leatrix** [comment]
Though the in-game cinematic runs fine, I saw the opening cinematic (during login) freeze on the PTR (11.0.7).  It's caused by 'Keep audio synced' ('System').  If you use this option, update to the latest alpha (11.0.21.alpha.x) or wait a few hours for the regular weekly update.  The update prevents the audio from being synced if a cinematic is being played at the time.  Thank you for your report.

**Comment by leatrix** [comment]
In the latest releases for all game flavors, the audio will not be synced if a cinematic is playing at the time and the freeze no longer occurs.

**Comment by HerrTiSo** [comment]
> In the latest releases for all game flavors, the audio will not be synced if a cinematic is playing at the time and the freeze no longer occurs.

Wow, that was faster than expected - incredible work, thank you!
