### ISSUE TITLE
Feature Request - Add Option to Mute All Race Combat Sounds under 'System > Game Sounds' (Cataclysm Classic)

### ISSUE THREAD

**Issue by Somatics23** [leatrix/leatrix-plus#248]
### Issue

Hello, I am simply requesting a feature to add all the grunting and groaning done by all of the races in Cataclysm Classic in combat, melee hits done, melee hits received, critical strikes done, critical strike received, the whole thing.. According to old forum/reddit posts, this used to be a feature of LTP called 'Combat Sounds' and they were all mutable, thank you for reading!

### Game version

Cataclysm Classic

**Comment by leatrix** [comment]
Just to clear up the confusion.  A few expansions ago, Blizzard added lots of screaming sounds for specific character spells. 
 There is a setting in Leatrix Plus retail called 'Shouts' (part of 'Mute game sounds') which silences these screaming sounds.  There has never been a setting to silence the original racial sounds because they are much more subtle and some of these sounds are used by enemy creatures as well as allies.  You can always press CTRL/S to toggle all sound effects.
