### ISSUE TITLE
Silent Warforged Nightmare mount

### ISSUE THREAD

**Issue by Neurotoxin001** [leatrix/leatrix-plus#34]
Can you please make silent option for https://www.wowhead.com/item=112326/warforged-nightmare

**Comment by leatrix** [comment]
I kept this open but didn't add a setting for the mount (yet).  If you want to know the sound file IDs so that you can mute the mount yourself with MuteSoundFile, open [Leatrix Sounds](https://www.curseforge.com/wow/addons/leatrix-sounds) and search for **clockwork_horse** (ensure the dropdown is set to Sound Files).  All the sound IDs are there.
