### ISSUE TITLE
Automate quests spending Stygia on The Cost of Death

### ISSUE THREAD

**Issue by Burzolog** [leatrix/leatrix-plus#37]
Automate quests is not supposed to turn in quests that cost a currency to complete, but it is currently turning in [The Cost of Death](https://www.wowhead.com/quest=64541/the-cost-of-death), which is a weekly quest to get rep with Venari by spending Stygia. Quest ID is 64541.

**Comment by leatrix** [comment]
For me, it's working fine.  Leatrix Plus stops The Cost of Death from turning in automatically at events QUEST_PROGRESS (the window with the Continue button) and QUEST_COMPLETE (the window with the Complete Quest button).  The Leatrix Plus function QuestRequiresCurrency() returns true for both events so Leatrix Plus doesn't turn-in the quest automatically.  It's working as intended.

Next time you are ready to turn-in the quest, disable all other addons except Leatrix Plus and see what happens then.  If the quest isn't turned-in automatically, another addon is causing it.

**Comment by Burzolog** [comment]
Sure, I'll definitely try to troubleshoot this myself after next reset.

**Comment by Burzolog** [comment]
I figured it out. The problem is [Immersion](https://www.curseforge.com/wow/addons/immersion). Leatrix Plus can't tell what items are required to complete a quest when Immersion is replacing the default quest frame with its own custom frame. I don't know if you or the developer of Immersion could possibly fix that interaction even if you wanted to.

**Comment by leatrix** [comment]
QuestRequiresCurrency() works by iterating through required quest progress items to see if any of them are of type currency or crafting reagent.  However, Immersion breaks this because it unregisters QuestFrame events and this causes QuestRequiresCurrency() to return nil.

Try the latest alpha (at least 9.1.06.alpha.1).  It registers QUEST_PROGRESS and QUEST_COMPLETE events after Immersion has loaded (if it's installed) so that QuestRequiresCurrency() can work correctly.

Note that I don't use Immersion.  I only browsed the code briefly to see why QuestRequiresCurrency() breaks when it's installed.

https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by Burzolog** [comment]
I can confirm that the fix is working for me. Thanks so much for helping me out even though it wasn't actually your addon's fault!
