### ISSUE TITLE
Player Frame gets stretched to max and reset to the Original Position upon entering a vehicle like Object

### ISSUE THREAD

**Issue by Goldenshacal** [leatrix/leatrix-plus#52]
Only LTP active.

When entering a vehicle like object, for example the Cushion Toy, the Player Frame gets stretched to max and reset to the Original Position. Means my entire left screen is my Playerframe.

Can be replicated every time, reload fixes it. Doesnt produce an Lua Error

**Comment by leatrix** [comment]
This is an issue with the default UI in 9.1.5, not with Leatrix Plus.

- Disable all addons (including LTP).
- Right-click PlayerFrame > Move frame > unlock frame (if it isn't unlocked already).
- Drag PlayerFrame to a new location (I suggest the middle of the screen).
- The frame appears to be saved in its new location without issue.  If you reload your UI at this point, the frame will still be in its new location and all looks fine.
- Enter a vehicle that has an exit button (such as the Cushion toy or Darkmoon Faire toys).
- The vehicle textured PlayerFrame will show but it will be in it's default top-left location - not where you moved PlayerFrame to.
- Click the vehicle Exit button and the regular PlayerFrame will also be in its default top-left position.  Your saved location has been forgotten.

Sometimes when you move PlayerFrame, you might see a Lua error mentioning the animation system.  This is with all addons disabled.

`Interface\FrameXML\AnimationSystem.lua:61: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: PlayerFrame:SetPoint.`

I reported it to Blizzard shortly after patch 9.1.5 went live for EU but until they fix it, there isn't anything that I can do.  However, since it's an issue which affects the default UI (not solely addon related) then it will probably be a priority for them.

**Comment by Goldenshacal** [comment]
Ok thanks.

**Comment by leatrix** [comment]
If you're using 'Manage frames' ('Frames'), just reload your UI (/rl) after exiting a vehicle.  PlayerFrame will be back to your saved location and all will be well again.

**Comment by leatrix** [comment]
Couple of forum posts about this issue:

- https://us.forums.blizzard.com/en/wow/t/hunter-pet-health-bar-disappears-whenever-i-enter-a-vehicle/1127383
- https://us.forums.blizzard.com/en/wow/t/lua-errors-when-enteringexiting-vehicles/1129734

**Comment by leatrix** [comment]
Until Blizzard fix it, one solution for now is to reset the frame positions.  Open the 'Manage frames' ('Frames') configuration panel and click the reset button.  The player frame will be reset to the top-left area of the screen and will no longer break when using a vehicle.

In one of the forum posts linked above, someone suggested deleting the layout-local file.  There's no need to do this is you're using 'Manage frames' because Leatrix Plus doesn't use layout-local.

**Comment by leatrix** [comment]
Blizzard still haven't fixed the bug (yet) so I added a temporary fix in 9.1.23.alpha.11 (or higher).  To use the temporary fix, you need to have 'Manage frames' ('Frames') enabled.  When entering or exiting a vehicle, the player frame will be restored to your chosen location as soon as you leave combat.  This temporary fix will be removed once Blizzard fix the bug with the player frame and vehicles.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by leatrix** [comment]
The latest fix in 9.1.25 fixes the rare issue where the player frame might occasionally disappear.  The default UI is still broken but I haven't seen a single issue with the 9.1.25 fix.

**Comment by leatrix** [comment]
Blizzard have now fixed the player frame bug in the default UI so the temporary fix has been removed in the latest alpha.

https://www.curseforge.com/wow/addons/leatrix-plus/files/all
