### ISSUE TITLE
Feature request: Auto accept invite from players in the same in-game community

### ISSUE THREAD

**Issue by zeenk** [leatrix/leatrix-plus#59]
I've been using a community2raid addon to invite all my alts on different realms so I don't have to do /inv name-realm every time I'm trying to mass invite my alts while doing stuff on more than 1 account, would be nice if there was a feature that could accept the group invite if they are in the same in-game community so I don't have to clog up my friends list with all my alts to be able to use the guildie and friends auto accept option. :)

**Comment by leatrix** [comment]
I don't know whether you closed this because of the pull request or because you changed your mind.

If the former, try 9.1.23.alpha.4.  It includes a new option called 'Friendly communities' ('Social').  If enabled, members of your communities will be treated as friends for all of the options on the 'Social' page.  If you use it, let me know how you go on with it.

**Comment by AlexFolland** [comment]
9.1.23.alpha.9 seems to work well for me, in the part that I could test.  @zeenk told me in Discord that he will test this tomorrow as he's busy all day today.  His testing setup for this is better than mine, as he can test on multiple accounts.  So, I'd wait for that before closing this.

**Comment by zeenk** [comment]
Yeah I closed it when Alex submitted the pull request and we got it to work with our testing, Thanks you for putting it in to the offical addon, will be very useful for me :) 👍
