### ISSUE TITLE
Get back default covenant button on minimap

### ISSUE THREAD

**Issue by Neurotoxin001** [leatrix/leatrix-plus#64]
Why did you change it:
![image](https://user-images.githubusercontent.com/39812401/145344852-0df94485-77f8-47ef-b8f9-3287d8b6f825.png)
when "Enhance minimap" is enabled? Your new button is overlapping LFG button when it's active. And I can't disable it without disable whole "Enhance minimap".

**Comment by leatrix** [comment]
The queue button issue is fixed in the latest alpha.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

The button was changed because the original button is huge, it's size and texture changes between characters and it doesn't fit well with the other buttons.  With square minimap, it doesn't fit at all.

**Comment by leatrix** [comment]
Added to 9.1.31.alpha.4 (or higher).
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

There is a new setting (disabled by default) that lets you choose whether you want to use the new covenant button for the round minimap. So if you want the classic look, you can now choose that. The square minimap will always use the new covenant button regardless of this new setting.
