### ISSUE TITLE
Settings doesnt work even after reinstalling

### ISSUE THREAD

**Issue by Skarlock** [leatrix/leatrix-plus#69]
Hello I have a problem, after the last update of Leatrix plus my complete interface settings were reset, however I can click the settings buttons but no new window opens to adjust e.g. the character portrait size. Even after reinstalling nothing changes

**Comment by leatrix** [comment]
Disable all other addons and try again.  If a configuration button (cogwheel) doesn't do anything when clicked, it's usually because the addon has failed to load correctly and that's usually because of a conflict with another addon.

If you were using 'Enhance minimap' ('Interface') before, it's probably because you have a minimap replacement or button manager addon installed but 'Enhance minimap' now has its own minimap replacement and button manager.  So you may find that you can remove your minimap replacement or button manager addon and just use the new 'Enhance minimap' instead.
More here: https://github.com/leatrix/leatrix-plus-bcc/issues/76#issuecomment-997133115

**Comment by Skarlock** [comment]
thanks it really helped! Now I also found out which addon is the problem: it was TomCat's Tours, I don't know why but I guess i just disable it now ^^, thanks again

**Comment by leatrix** [comment]
Many thanks for your valuable feedback.  After looking into it, this is caused by TomCatTours using a non-standard minimap button that wasn't returning a button texture.  I added a fix for it (and any other addons that do this, though I haven't come across any) in 9.1.34 so LTP no longer shows a Lua error on startup when TomCatTours is installed.

I added the same fix to the latest releases of Classic and BCC too (though nobody has reported any issues there presumably because TomCatTours doesn't have a minimap button in Classic/BCC).

If you leave any feedback for TomCatTours, please ask the author to use a standard LibDBIcon button instead of a custom,non-standard button.  Non-standard buttons don't help anything and shouldn't be used.  Most addons (at least 80% when I last looked) already use the LibDBIcon library for thier minimap buttons so have no issue but a few still use non-standard buttons.
