### ISSUE TITLE
Minimap scaling issue

### ISSUE THREAD

**Issue by palacode** [leatrix/leatrix-plus#70]
Hi, thanks for this great addon, i've been using it for years mainly for minimap scaling. I forgot how small the original minimap is. 

Since the update on December 1st, Enlarging minimap does not move objectives and vehicle frame down so minimap covers those frames. It works fine if i reinstall the version 9.1.24. 

This happens even when I disable all other addons. I also tried deleting WTF folder to see if my settings are causing the issue. Maybe i am missing another setting to move objectives or vehicle frame, can you please help this issue?

Thanks

**Comment by leatrix** [comment]
The original minimap scale slider changed because the 'Enhance minimap' option received a big overhaul and now you can move the minimap anywhere on-screen, resize it, rescale it, make it square shape, hide addon buttons and group all addon buttons together in a little frame.

The minimap scale slider looks the same but before it would scale the entire minimap cluster (which in turn would affect everything attached to the cluster in some way such as buffs, objectives tracker and right-side action bars - this is what you're referring to).  Whereas now the scale slider only scales the minimap and not the entire cluster so frames attached to the cluster are no longer affected by the scale slider.

Howeve,r in the latest alpha (9.1.35.alpha.3 or higher), you can adjust the cluster scale once again using a new cluster scale slider - in addition to rescaling and resizing the minimap itself.  Note that the caveat is the same as before - adjusting the cluster scale will adjust the scale of the default UI right-side action bars when you login so if you use the default UI right-side action bars, you may want to leave the cluster scale at 100%.

Leatrix Plus is updated regularly and sometimes new features are added.  You can see what's new in the change log which you can access from the addon page in CurseForge App or the files page on the CurseForge website.
