### ISSUE TITLE
Minimap: Conflict with GRM button

### ISSUE THREAD

**Issue by tflo** [leatrix/leatrix-plus#71]
Using the Lea-enhanced minimap I can no longer disable the minimap button of the [GRM](https://www.curseforge.com/wow/addons/guild-roster-manager) add-on. (Before, I could enable/disable it via GRM settings.)

Tinkered around with Lea’s minimap settings, but can’t get it to work. I think this behavior started only today with Leatrix 9.1.35.alpha.4, but not 100% sure.

I also noticed (in case it helps): 
*  The GRM add-on button has lost its tooltip. Now it shows just the button name (“GRM_MinimapButton”) when hovering over.
* _Sometimes_ after a reload the button also loses its icon and shows some blue-circle icon instead.
* Lea somehow seems to have created a new LDB plugin from the button, called “LeaPlusCustomIcon_GRM_MinimapButton”. It’s visible in Bazooka’s plugin list and can be disabled there.

**Comment by leatrix** [comment]
Thank you for putting so much detail into your ticket.  That's much appreciated.  And now for the long answer...

Most addon authors use LibDBIcon for their minimap buttons and these work perfectly with 'Enhance minimap'.  However, a few addon authors don't use LibDBIcon so 'Enhance minimap' has to replace their custom buttons with LibDBIcon buttons.

As 'Enhance minimap' has to create a LibDBIcon button for the addon, there are minor issues you just need to be aware of.  If you use the relevant addon's configuration panel to toggle the button, you may need to reload your UI to see the changes (I should note this in the help button tooltip).  This is because 'Enhance minimap' only checks to see if the custom button is visible when you login but then doesn't check again.  If the button is visible, 'Enhance minimap' replaces it with a LibDBIcon button when you login.  If it's not visible, a LibDBIcon button isn't created and therefore isn't shown.

In GRM's case, GRM does actually show the button briefly during login so a LibDBIcon button is created at that point.  This is the problem with buttons that don't use LibDBIcon - there is no standard, uniform way of checking them, interacting with them or controlling them because they all use their own custom, unique code.

You won't see custom addon button tooltips (and in rare cases not the texture either) because it's not the original button but a LibDBIcon replacement.  'Enhance minimap' tries to get the texture of the custom button (and succeeds in most cases) but again, custom buttons all use unique code so it's not always possible.  The button remains fully functional, however.

LibDBIcon buttons are essential for 'Enhance minimap' to work correctly.  Custom buttons don't automatically hide, don't get sized correctly, don't get put in the button frame and don't follow the shape of the minimap so can't be positioned correctly.

This is why, with many minimap addons, custom buttons can only be moved round in a circle (even if you use a square minimap) and don't automatically hide along with LibDBIcon buttons.  I know that you used to use 'BasicMinimap' ([from your previous ticket](https://github.com/leatrix/leatrix-plus/issues/66)) and this is exactly what happens with that addon (and others).  'Enhance minimap' attempts to solve this and more issues by replacing custom buttons with LibDBIcon buttons.

Over 80% of addons use LibDBIcon for their minimap buttons already.  Please ask the authors of the few addons that don't to start doing so then their addon buttons will work flawlessly with 'Enhance minimap' and other minimap addons.

**Comment by leatrix** [comment]
In the latest alpha releases (for all games), I added a further check for the rare cases where non-LibDBIcon minimap button textures aren't available.  So GRM and TomCatTours minimap buttons now have the correct textures (and maybe other addons that have the same texture structure).

If you come across other non-LibDBIcon buttons that don't have the correct textures, please let me know and perhaps I can add further checks (it all depends on how unique the non-LibDBIcon code is).

**Comment by tflo** [comment]
Thank you for the very detailed explanation.

> If you use the relevant addon's configuration panel to toggle the button, you may need to reload your UI to see the changes 

Of course I did reloads while trying. In fact, I even did several log-out/in, since I was cycling through my alts when I observed the issue.

Just to be sure, I tried it again now with the new 9.1.35.alpha.5, and with reloads between disabling/enabling/disabling the GRM button via GRM config tab.

The button still refuses to go away ;)

Maybe it wasn’t clear from my OP: I’m not interested at all in seeing the GRM button. It is pretty redundant, and I had it disabled all the time before (with BasicMinimap, and also with Lea up to –probably– alpha4). 
I mentioned the missing icon and tooltip only as a potential debugging help for you. (But I see now that you are already completely aware of that sort of issue.)

Maybe the easiest solution: _Add an option to Lea’s Minimap config that simply suppresses all non-standard buttons._ So, if a user has a nasty button you can’t fix, he still can get to enjoy a clean Lea minimap.

BTW, [ZonePet](https://www.curseforge.com/wow/addons/zonepet) is another add-on with a non-standard minimap button (it moves in a circle). But, contrary to GRM, this button goes away when I disable it in the add-on’s config :)

**Comment by leatrix** [comment]
As I said, a LibDBIcon button is only created if the custom (original) button is shown during login.  In GRM's case, the custom button is shown briefly when the LibDBIcon buttons are being created so a LibDBIcon button is created for GRM.

ZonePet uses a very custom, locked down button so that will just have to stay as it is.  Even adding a setting to hide all custom buttons wouldn't hide the ZonePet button.

For cases like GRM and ZonePet, please ask the author of such addons to do the right thing and use the standard LibDBIcon library for their minimap buttons as over 80% of addons do already.

**Comment by tflo** [comment]
Don’t worry, I opted for the brute-force approach and commented out the relevant minimap code in GRM ;) 
(Since the add-on isn’t updated very frequently, this is low maintenance for me.)

But – just in theory –, wouldn’t it be a solution if the Lea minimap code would run with a small delay after login, so that GRM or similar add-ons could briefly show their minimap button without being “caught” by Lea? Just a thought…

Many thanks for your efforts, and for the great add-on, of course.

– Tom

**Comment by leatrix** [comment]
If you wish to edit addon code and want a LibDBIcon button for ZonePet, just enter this just before the end of the `ZonePet:Initialize()` function in ZonePet.lua (directly below the `ZonePet_addInterfaceOptions()` line).

```
local miniButton = LibStub("LibDataBroker-1.1"):NewDataObject("ZonePet", {
	type = "data source",
	text = "ZonePet",
	icon = "Interface\\ICONS\\Tracking_WildPet",
	OnClick = function(self, btn)
		zonePetMiniMap.Button:Click(btn)
	end,
	OnTooltipShow = function(tooltip)
		if not tooltip or not tooltip.AddLine then return end
		tooltip:AddLine("ZonePet")
	end,
})

local icon = LibStub("LibDBIcon-1.0", true)
icon:Register("ZonePet", miniButton, zonePetMiniMap)
zonePetMiniMap.Button:Hide()
```
It will work as long as LibDBIcon has been loaded (by another addon) before ZonePet starts loading (most addons with minimap buttons will load LibDBIcon).

If for some reason LibDBIcon hasn't loaded by another addon before ZonePet starts loading, install LibDBIcon from CurseForge (just like any other addon) then edit ZonePet.toc and add this below the other ## lines (directly below the X-Category line):

`## OptionalDeps: LibDBIcon-1.0`

Then reload.  You now have a fully compatible LibDBIcon for ZonePet.  It's easy and saves a lot of coding for the author because Funkehdude has done it all for them.  The LibDBIcon will work perfectly with all of 'Enhance minimap' settings and the button position is saved automatically in the ZonePet settings file.

**Comment by tflo** [comment]
Thanks for this solution. I have [linked](https://github.com/trozware/ZonePet/issues/2#issue-1085328797) your comment to the author of ZonePet, maybe he/she is going to implement it.

***

Back to the issue with GRM: 

I’ve just seen in the change log that in earlier Lea versions the ‘Replace non-standard buttons’ was still optional. Making this optional again would eliminate the problem with buttons not being able to be disabled.

Please note that I appreciate your efforts to fix the buttons; this is probably more than any of the dedicated minimap add-ons do. However, for people who prefer to have as few buttons on the minimap as possible, this feature is of limited use and apparently may even cause new problems.

And if it happens that the few buttons I actually have on the minimap are already fully compatible (LibDBIcon), then even the Hide and the Combine feature would probably work fine with the Replace fix disabled, no?

**Comment by leatrix** [comment]
Hopefully the ZonePet author will use a LibDBIcon button in an update.  Obviously, if the author adds a LibDBIcon button, they shouldn't require users to install LibDBIcon from CurseForge (that was just to demonstrate how easy it is to add) but should run the LibDBIcon files directly from the toc file, such as:

```
LibDBIcon-1.0\LibStub\LibStub.lua
LibDBIcon-1.0\CallbackHandler-1.0\CallbackHandler-1.0.lua
LibDBIcon-1.0\LibDataBroker-1.1\LibDataBroker-1.1.lua
LibDBIcon-1.0\LibDBIcon-1.0\LibDBIcon-1.0.lua
```

(changing paths if needed).

'Replace non-standard buttons' was removed because I want 'Enhance minimap' to run in the way that it is designed to run.  If custom buttons aren't replaced, then the buttons are not scaled properly (and some are huge), they don't follow the minimap shape so positioning them is difficult, they don't hide automatically and they can't be added to the button frame.

By replacing them with LibDBIcon buttons, all of the features of 'Enhance minimap' work great except for a few addons that have weird or locked down minimap buttons.

If custom buttons share something in common so that I can add a check for a group of them that share some characteristic, I can add that to ensure a LibDBIcon button is created.  That's what I did with GRM and TomCatTours.

I don't want to add a setting to hide LibDBIcon buttons that were created to replace custom buttons because a LibDBIcon won't be created if the button is not showing when you login and that typically works fine.

With that said, please try 9.1.35.alpha.6.  The GRM button no longer shows for me as long as it's disabled in GRM options.  As I said before though, toggling the button in GRM configuration panel requires a UI reload for the change to take effect.

**Comment by tflo** [comment]
> With that said, please try 9.1.35.alpha.6.

You have made it, it works perfectly now!
(I’ve seen you added a timer for MakeButtons. So, my thought from before wasn’t that stupid after all ;)

Many thanks for this, highly appreciated!

Let me know if you need more add-ons with crappy buttons. I’m sure I can find some for you :)

**Comment by leatrix** [comment]
Yes, I added the magical 0.1 second delay (a tenth of a second).  I use that everywhere (16 times in Leatrix Plus for Shadowlands).  It solves lots of problems.  When in doubt, add a tenth of a second delay.  It'll work then.  If you find more addons with broken custom buttons, please do report them to me (but also report to the addon author and ask them to use LibDBIcon).

**Comment by trozware** [comment]
> Hopefully the ZonePet author will use a LibDBIcon button in an update. Obviously, if the author adds a LibDBIcon button, they shouldn't require users to install LibDBIcon from CurseForge (that was just to demonstrate how easy it is to add) but should run the LibDBIcon files directly from the toc file, such as:

Thanks very much for these instructions.
I have implemented them and now the ZonePet minimap button is using LibDBIcon.

I have one issue to solve before releasing. I have a setting that users can toggle to hide or show the minimap button.
This works perfectly if Leatrix Plus is showing the minimap buttons individually.

However when combining the buttons, the ZonePet button always appears.

I am using `icon:Hide("ZonePet")` to toggle the minimap button off. 
What do I need to add to hide or show it in the combined display?

**Comment by leatrix** [comment]
Is the code available somewhere for me to try?

**Comment by trozware** [comment]
> Is the code available somewhere for me to try?

Yes, I have not released it on CurseForge yet, but I've pushed the new code to:
https://github.com/trozware/ZonePet

**Comment by leatrix** [comment]
You need to use this when you show or hide the icon:

zonePetMiniMap.hide = false

(or true)

**Comment by trozware** [comment]
Thanks very much - that fixed it.

**Comment by leatrix** [comment]
And because I did this for BCC... I have done it again for Shadowlands.

I installed the top 200 addons (from CurseForge) in Shadowlands.

Out of the top 200 addons, around 36 use minimap buttons.  Out of those 36, only two have slight hiccups.

Infinite Raid Tools uses a custom minimap button with too few regions (two to be exact).  Sadly, the author chose to duplicate LibDBIcon's native on-hover functionality rather than use the standard library so it's not fully compatible.

The only other small hiccup is Narcissus.  Again, it uses a custom button but it's no problem because Enhance minimap replaces it with a LibDBIcon button.  However, the original button texture is too large for Enhance minimap to recognise so it gives the button a generic texture.  The button itself is functional though.

Every other addon in the top 200 works perfectly.
