### ISSUE TITLE
Request: Ability to mute the sound from SL glad mounts.

### ISSUE THREAD

**Issue by mango201** [leatrix/leatrix-plus#77]
Hi would it be possible to add the ability to mute the shadowlands Soul eater mounts. They seem to have the maw background music when riding the mount.

Sinful Gladiator's Soul Eater
Unchained Gladiator's Soul Eater
and the upcoming one:
Cosmic Gladiator's Soul Eater

**Comment by leatrix** [comment]
Added to 9.1.38.alpha.3.  New setting in 'Mute game sounds' called 'Soul Eaters'.
But please test it out and let me know if it works because I'm not able to test it.
If you're mounted on a Soul Eater mount when you install the update, dismount and mount up again after checking the 'Soul Eaters' box to test it.
https://www.curseforge.com/wow/addons/leatrix-plus/files/all

**Comment by mango201** [comment]
Thanks, just tried it on 9.1.38.alpha.3 and it works good.
